default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_DB_POOL_SIZE") { "5" } %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || "5432" %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>

development:
  <<: *default
  database: little_ruby_development

test:
  <<: *default
  database: little_ruby_test

production:
  <<: *default
  database: little_ruby_production